### PR TITLE
Added mod operator

### PR DESCRIPTION
**Pull request by mrshu**
As described in #79 and with help provided by @rzimmerman in #78 I've implemented (if we can call that implementing) the mod operator.

### CODE REVIEW

**Comment by dijs** [comment]
I cannot get the modular operator to work at all...

console.log 5 % 2

gives the error: invalid token '% 2...'

**Comment by mrshu** [comment]
@rompetoto Well, it was decided that `mod` will be the modular operator (see the discussion at #79). On my pull request's branch I can do

```
kal> console.log 5 mod 2
1
```

Which I find satisfactory. Does that work for you too?

**Comment by dijs** [comment]
Sure that would work!

It is not on master yet right?

**Comment by mrshu** [comment]
@rompetoto It is now =)

**Pull request merged**
