### PR TITLE
Minor Changes to tests

### PR DESCRIPTION
**Pull request by baldawarishi**
Adding %= operator
Few Spaces
Removed an extra newline

### CODE REVIEW

**Comment by rzimmerman** [comment]
Rishi-

I'm actually against having a `%=` operator for aesthetic reasons. I'd rather have the user type `a = a mod 5` (I don't even like `%` for modulus). I've even considered removing `/=` and `*=` since they aren't that useful. `+=` and `-=` are pretty clear in my opinion.

Any thoughts? I don't think I ever implemented `mod` or `%` if anyone wants to take a crack at it.

**Comment by mrshu** [comment]
@rzimmerman I'd love to implement `mod` as I find it more aesthetically pleasing (given for instance the context of beginners).

Where do you think I should start? Can you please point me to some direction (maybe provide with some hints)? 

Thanks!

**Comment by rzimmerman** [comment]
@mrshu, This shouldn't actually be that bad and it's a good way to get used to the codebase.

I'd start by making the grammar actually accept it. Under the grammar.kal file, check out the class for `BinOp`. The last line has a list of valid `IDENTIFIER` tokens for a binary operation.

You'll also need to support it in generator.kal. The `me.BinOp.prototype.js` function returns JavaScript. You'll probably need to update the `KEYWORD_TRANSLATE` mapping.

That should be it, but please add a test case if you make changes and make sure it passes using `npm test`.

Thanks!

**Comment by rzimmerman** [comment]
@mrshu - also don't forget to do
`npm run-script make`
before running
`npm test`

Otherwise you're not testing your changes.

**Comment by mrshu** [comment]
@rzimmerman Thanks, I'll try to implement it and then report back.

**Comment by mrshu** [comment]
@rzimmerman I did what you asked me to and very probably failed to follow them.

Right now this

```
i = 5 mod 2
```

will get translated to this

```
(function () {var i;
i = 5;
%(2);})()
```

What do you suggest? I strongly suspect ti will be some very simple problem.

**Comment by rzimmerman** [comment]
Ah, pretty close. In the grammar.kal file, you allowed the user to use `%`, but then in generator.kal you are expecting `mod`.

In grammar.kal, in `BinOp`, instead of adding the `%` token to allowed literals:

``` kal
if me.op.type is 'LITERAL'
      me.error("unexpected operator #{this.op.value}") if me.op.value in [')',']','}',';',':',',']
      me.lock()
      me.error("unexpected operator #{this.op.value}") unless me.op.value in ['+','-','*',','/','>','<','^','<=','>=','==','!=']
```

Instead add `mod` to the allowed tokens:

``` kal
    else
      if me.op.value is 'not'
        me.op = me.req_val 'in', 'of'
        me.invert = yes
      me.error("unexpected operator #{this.op.value}") unless me.op.value in ['and','but','or','xor','nor','in','is','isnt','instanceof','of','mod']
```

Right now I think it's treating `mod` as a function, then translating the token for some reason.

**Comment by rzimmerman** [comment]
Oh, also you should add `mod` to sugar.kal's `NOPAREN_WORDS`. And grammar.kal's `KEYWORDS`. Because Kal allows you to call functions without parentheses, something like `a mod b` would normally get transformed in sugar.kal to `a(mod(b))`. Specifying `mod` as a noparen word and keyword will prevent this.

**Pull request closed without merging**
